---
title: "Assignment Spring 2025 Report"
author: "Manh Cuong Ha"
date: "2025-10-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div style="text-align: center;">

## **Subject:** COMP7024 - Programming for Data Science
## **Name:** Manh Cuong Ha
## **Student Number:** 22118525

<br><br><br><br><br><br><br><br><br><br>

---

### **Declaration**

</div>

> By including this statement, we the authors of this work, verify that:
>
> * We hold a copy of this assignment that we can produce if the original is lost or damaged.
> * We hereby certify that no part of this assignment/product has been copied from any other student’s work or from any other source except where due acknowledgement is made in the assignment.
> * No part of this assignment/product has been written/produced for us by another person except where such collaboration has been authorised by the subject lecturer/tutor concerned.
> * We are aware that this work may be reproduced and submitted to plagiarism detection software programs for the purpose of detecting possible plagiarism (which may retain a copy on its database for future plagiarism checking).
> * We hereby certify that we have read and understand what the School of Computing, Engineering and Mathematics defines as minor and substantial breaches of misconduct as outlined in the learning guide for this unit.


\newpage